#!/bin/sh

. /opt/graphite/bin/activate
PYTHONPATH="/opt/graphite/lib:/opt/graphite/lib/python2.7/site-packages:/usr/lib/python2.7/dist-packages"
export PYTHONPATH
DJANGO_SETTINGS_MODULE=graphite.settings
export DJANGO_SETTINGS_MODULE

exec /opt/graphite/bin/uwsgi --ini /opt/graphite/uwsgi.ini
